name: Deploy NDawn Theme To Shadow Walker
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - master
jobs:
  deploy-on-push-to-master:
    if: github.event_name == 'push'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set release date
        run: |
          echo "TIME=$(date +%Y-%m-%d-%H-%M)" >> ${GITHUB_ENV}
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: ndawn-${{ env.TIME }}

  deploy-on-pr-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set release date
        run: |
          echo "TIME=$(date +%Y-%m-%d-%H-%M)" >> ${GITHUB_ENV}
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: ndawn-${{ env.TIME }}
