name: Deploy NDawn Theme To Shadow Walker
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: set release date
        run: |
          echo "TIME=$(date +%Y-%m-%d-%H-%M)" >> ${GITHUB_ENV}
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.5.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: ndawn-${{ env.TIME }}
